var gvjs_bT="border: 0; padding: 0; margin: 0;";gvjs_bI.prototype.OE=gvjs_V(67,function(a){this.ticks=a});gvjs_1I.prototype.OE=gvjs_V(66,function(a){gvjs_bI.prototype.OE.call(this,a);var b=0;gvjs_u(this.ticks,function(c){c=this.Xq(c);b=Math.max(b,gvjs_pA(c/this.dfa))},this);this.h9=b});
function gvjs_cT(a,b,c,d,e){gvjs_H.call(this);this.ma=a;this.ga=b;this.Pa=c;this.Fga=new gvjs_ly({bb:gvjs_ft,fontSize:d,color:gvjs_nr,opacity:1,Lb:"",bold:!1,Nc:!1,Ue:!1});this.Yya=new gvjs_ly({bb:gvjs_ft,fontSize:d,color:gvjs_rt,opacity:1,Lb:"",bold:!1,Nc:!1,Ue:!1});this.Wxa=new gvjs_ly({bb:gvjs_ft,fontSize:0,color:gvjs_nr,opacity:1,Lb:"",bold:!1,Nc:!1,Ue:!1});this.tva=e;this.Um=this.ab=this.F=null;this.K2=[]}gvjs_o(gvjs_cT,gvjs_H);gvjs_=gvjs_cT.prototype;gvjs_.lf=function(){return this.Xa};
gvjs_.Ow=function(a){this.Xa=a};gvjs_.kf=function(){return this.Cb};gvjs_.bu=function(a){this.Cb=a};gvjs_.Wa=function(a,b,c){this.$d=a;this.RY=b;this.ku();a=gvjs_dT(this,a);null!=this.ZJ&&c?(this.Tf=new gvjs_1E([this.ZJ],[a],c.duration,c.easing),gvjs_G(this.Tf,["begin","animate",gvjs_R],this.fua,!1,this),gvjs_G(this.Tf,gvjs_R,this.eua,!1,this),this.Tf.play(!1)):(this.ZJ=a,gvjs_eT(this))};gvjs_.OE=function(a,b){this.sca=Math.max(1,a);this.PD=Math.max(1,b)};gvjs_.P3=function(a){this.Iz=a};
function gvjs_fT(a,b,c,d){a.K2.push({hf:b,ol:c,color:d})}gvjs_.setAnimation=function(){};gvjs_.clear=function(){this.ku();gvjs_E(this.ab);this.ab=null;gvjs_li(this)};gvjs_.draw=function(a,b){var c=new gvjs_A(this.ga,this.Pa);null==this.ab?this.ab=new gvjs_3B(this.ma,c,a,b):this.ab.update(c,a);this.ab.rl(gvjs_s(this.no,this),a)};
gvjs_.no=function(){var a=this.ab.Oa(),b=a.Lm(this.ga,this.Pa);a.ic(b,gvjs_3t,gvjs_Lz);this.F=a;var c=this.Um=a.Sa(!1);a.appendChild(b,c);b=Math.round(.45*Math.min(this.ga,this.Pa));var d=this.ga/2,e=this.Pa/2;a.Ke(d-.5,e-.5,b,gvjs_gT,c);b-=gvjs_gT.strokeWidth;b=Math.round(.9*b);a.Ke(d-.5,e-.5,b,gvjs_hT,c);b-=2*gvjs_hT.strokeWidth;var f=.75*b;for(var g=0;g<this.K2.length;g++){var h=this.K2[g],k=gvjs_iT(this,gvjs_dT(this,h.hf)),l=gvjs_iT(this,gvjs_dT(this,h.ol)),m=new gvjs_SA,n=d+gvjs_8y(k,b),p=e+
gvjs_9y(k,b);m.move(n,p);m.Sf(d,e,b,b,k+90,l+90,!0);n=d+gvjs_8y(l,f);p=e+gvjs_9y(l,f);m.va(n,p);m.Sf(d,e,f,f,l+90,k+90,!1);m.close();a.Ia(m,new gvjs_3({fill:h.color}),c)}if(this.QL||this.i5)this.QL&&(f=e-Math.round(.35*b),a.Zi(this.QL,0,f,this.ga,f,gvjs_0,gvjs_0,this.Fga,c)),this.i5&&(f=e+Math.round(.35*b),a.Zi(this.i5,0,f,this.ga,f,gvjs_0,gvjs_0,this.Fga,c));h=this.PD;k=.8*b;l=.9*b;n=this.sca*h;p=(this.Cb-this.Xa)/n;var q=new gvjs_SA,r=new gvjs_SA,t=this.Wxa,u=Math.round(.14*b);t.fontSize=u;for(g=
0;g<=n;g++){var v=gvjs_iT(this,gvjs_dT(this,g*p+this.Xa)),w=0==g%h,x=w?k:l;m=w?q:r;var y=d+gvjs_8y(v,x);f=e+gvjs_9y(v,x);m.move(y,f);y=d+gvjs_8y(v,b);f=e+gvjs_9y(v,b);m.va(y,f);w&&this.Iz&&(m=this.Iz[Math.floor(g/h)])&&(y=d+gvjs_8y(v,x-u/2),f=e+gvjs_9y(v,x-u/2),x=gvjs_0,280<v||90>v?(x=gvjs_R,v=0):90<=v&&260>v?(x=gvjs_2,v=y,y=this.ga):(w=Math.min(y,this.ga-y),v=y-w,y+=w,f+=Math.round(u/4)),a.Zi(m,v,f,y,f,x,gvjs_0,t,c))}a.Ia(r,gvjs_7ia,c);a.Ia(q,gvjs_8ia,c);this.ku();this.kda=b;gvjs_eT(this);this.tva()};
gvjs_.fua=function(a){this.ZJ=a.x;gvjs_eT(this)};gvjs_.eua=function(){this.ku()};gvjs_.ku=function(){this.Tf&&(gvjs_li(this.Tf),this.Tf.stop(!1),gvjs_E(this.Tf),this.Tf=null)};function gvjs_dT(a,b){a=(b-a.Xa)/(a.Cb-a.Xa);a=Math.max(a,-.02);return a=Math.min(a,1.02)}function gvjs_iT(a,b){return a.f7*b+gvjs_5y((360-a.f7)/2+90)}
function gvjs_eT(a){if(a.F){var b=a.kda,c=a.F,d=a.ga/2,e=a.Pa/2,f=gvjs_iT(a,a.ZJ),g=Math.round(.95*b),h=Math.round(.3*b),k=gvjs_8y(f,g);g=gvjs_9y(f,g);var l=gvjs_8y(f,h);h=gvjs_9y(f,h);f=gvjs_5y(f+90);var m=.07*b,n=gvjs_8y(f,m);m=gvjs_9y(f,m);f=new gvjs_SA;f.move(d+k,e+g);f.Jp(d+n,e+m,d-l+n/2,e-h+m/2,d-l,e-h);f.Jp(d-l-n/2,e-h-m/2,d-n,e-m,d+k,e+g);k=Math.round(.15*b);(g=a.jda)?c.qc(g):g=a.jda=c.Sa();a.RY&&(b=e+Math.round(.75*b),c.Zi(a.RY,0,b,a.ga,b,gvjs_0,gvjs_0,a.Yya,g));c.Ia(f,gvjs_9ia,g);c.Ke(d-
.5,e-.5,k,gvjs_$ia,g);c.appendChild(a.Um,g)}}var gvjs_gT=new gvjs_3({fill:gvjs_zr,stroke:gvjs_nr,strokeWidth:1}),gvjs_hT=new gvjs_3({fill:"#f7f7f7",stroke:gvjs_Ar,strokeWidth:2}),gvjs_7ia=new gvjs_3({stroke:gvjs_pr,strokeWidth:1}),gvjs_8ia=new gvjs_3({stroke:gvjs_nr,strokeWidth:2}),gvjs_9ia=new gvjs_3({fill:"#dc3912",fillOpacity:.7,stroke:"#c63310",strokeWidth:1}),gvjs_$ia=new gvjs_3({fill:"#4684ee",stroke:gvjs_pr,strokeWidth:1});gvjs_=gvjs_cT.prototype;gvjs_.Xa=NaN;gvjs_.Cb=NaN;gvjs_.sca=NaN;
gvjs_.PD=NaN;gvjs_.$d=0;gvjs_.RY=null;gvjs_.QL=null;gvjs_.i5=null;gvjs_.f7=270;gvjs_.kda=0;gvjs_.jda=null;gvjs_.ZJ=null;gvjs_.Iz=null;gvjs_.Tf=null;function gvjs_jT(a,b,c,d){this.ma=a;this.ga=b;this.Pa=c;this.$O=d;this.Ky=[];this.mc=[];this.Iz=[];this.SY=[];this.Kq=[];this.Xa=0;this.Cb=100;this.g7=this.P2=this.yS=this.xS=this.k6=this.dV=this.cV=this.KZ=this.GP=this.FP=null;this.vr=!0;this.I1=0}gvjs_=gvjs_jT.prototype;gvjs_.Ow=function(a){this.Xa!=a&&(this.Xa=a,this.vr=!0)};gvjs_.lf=function(){return this.Xa};gvjs_.bu=function(a){this.Cb!=a&&(this.Cb=a,this.vr=!0)};gvjs_.kf=function(){return this.Cb};gvjs_.setAnimation=function(a){this.g7=a};
gvjs_.setValues=function(a,b,c){this.vr=this.vr||this.mc.length!=a.length||this.Kq.length!=c.length||!gvjs_Jy(this.Kq,c);this.mc=a;this.SY=b;this.Kq=c};gvjs_.P3=function(a){1==a.length&&(a=["",a[0],""]);gvjs_Jy(this.Iz,a)||(this.Iz=a,this.vr=!0)};function gvjs_kT(a,b,c){return Math.min(Math.floor(a.ga/c),Math.floor(a.Pa/b))}gvjs_.draw=function(a){if(this.vr)gvjs_aja(this,a);else for(a=0;a<this.mc.length;a++){var b=this.Ky[a];b.QL=this.Kq[a];b.Wa(this.mc[a],this.SY[a],this.g7)}};
function gvjs_aja(a,b){a.clear();var c=a.mc.length,d=1,e=1;if(1<c){var f=Math.floor(Math.sqrt(a.ga*a.Pa/c));e=Math.floor(a.ga/f);for(d=Math.floor(a.Pa/f);!(c<=Math.floor(a.ga/f)*Math.floor(a.Pa/f));){var g=gvjs_kT(a,d,e+1),h=gvjs_kT(a,d+1,e);g>=h&&(f=g,e++);h>=g&&(f=h,d++)}}f=gvjs_kT(a,d,e);f-=0;h=gvjs_Oh();h.qc(a.ma);a.Ky=[];if(0!=c){var k=h.J(gvjs_ss,{style:gvjs_bT,cellpadding:0,cellspacing:0,align:gvjs_0}),l=h.J(gvjs_ts,null);h.appendChild(k,l);g=[];for(var m=0,n=0;n<d;n++){var p=h.J(gvjs_vs,{style:gvjs_bT});
h.appendChild(l,p);for(var q=0;q<e;q++){var r=h.J(gvjs_us,{style:"border: 0; padding: 0; margin: 0; width: "+f+"px;"});g[m++]=r;h.appendChild(p,r)}}h.appendChild(a.ma,k);d=Math.round(.1*f);a.I1=0;a.vr=!0;for(e=0;e<c;e++)h=a.Ky[e]=new gvjs_cT(g[e],f,f,d,gvjs_s(function(){this.I1++;this.I1==this.Ky.length&&(this.vr=!1)},a)),h.Ow(a.Xa),h.bu(a.Cb),h.QL=a.Kq[e],k=a.Iz,l=k.length,h.OE(1<l?l-1:4,a.PD),0<l&&h.P3(k),h.Wa(a.mc[e],a.SY[e],null),null!=a.FP&&null!=a.GP&&gvjs_fT(h,a.FP,a.GP,a.KZ),null!=a.cV&&null!=
a.dV&&gvjs_fT(h,a.cV,a.dV,a.k6),null!=a.xS&&null!=a.yS&&gvjs_fT(h,a.xS,a.yS,a.P2),h.draw(b,a.$O)}}gvjs_.clear=function(){for(var a=0;a<this.Ky.length;++a)this.Ky[a].clear();this.Ky=[]};gvjs_.PD=2;function gvjs_lT(a){gvjs_Qn.call(this,a)}gvjs_o(gvjs_lT,gvjs_Qn);gvjs_=gvjs_lT.prototype;
gvjs_.Rd=function(a,b,c){var d=new gvjs_Aj([c||{}]);c=this.container;var e=this.La(d),f=this.getHeight(d),g=gvjs_K(d,gvjs_Eu);if(e!=this.ga||f!=this.Pa||g!=this.$O)this.xL&&this.xL.clear(),this.xL=new gvjs_jT(c,e,f,g),this.ga=e,this.Pa=f,this.$O=g;c=this.xL;e=gvjs_L(d,gvjs_Ov,0);c.Ow(e);e=gvjs_L(d,gvjs_Gv,100);c.bu(e);e=d.fa("majorTicks",[String(c.lf()),"","","",String(c.kf())]);c.P3(e);e=gvjs_L(d,"minorTicks",2);c.PD!=e&&(c.PD=e,c.vr=!0);e=d.Aa("greenFrom");f=d.Aa("greenTo");g=d.Aa("yellowFrom");
var h=d.Aa("yellowTo"),k=d.Aa("redFrom"),l=d.Aa("redTo"),m=gvjs_oy(d,"greenColor",gvjs_lr),n=gvjs_oy(d,"yellowColor",gvjs_wr),p=gvjs_oy(d,"redColor",gvjs_vr);if(c.FP!=e||c.GP!=f||c.KZ!=m||c.cV!=g||c.dV!=h||c.k6!=n||c.xS!=k||c.yS!=l||c.P2!=p)c.FP=e,c.GP=f,c.KZ=m,c.cV=g,c.dV=h,c.k6=n,c.xS=k,c.yS=l,c.P2=p,c.vr=!0;d=gvjs_5K(d,400,gvjs_cv);c.setAnimation(d);d=[];e=[];f=[];if(2==b.$()&&b.W(0)==gvjs_l&&b.W(1)==gvjs_g)for(g=0;g<b.ca();g++)null!=b.getValue(g,0)&&null!=b.getValue(g,1)&&(f.push(b.getValue(g,
0)),d.push(b.getValue(g,1)),e.push(b.Ha(g,1)));else for(h=0;h<b.$();h++)if(b.W(h)==gvjs_g)for(g=0;g<b.ca();g++)null!=b.getValue(g,h)&&(d.push(b.getValue(g,h)),e.push(b.Ha(g,h)),f.push(b.Ga(h)));c.setValues(d,e,f);c.draw(a);gvjs_I(this,gvjs_i,null)};gvjs_.He=function(){this.xL&&this.xL.clear()};gvjs_.ga=0;gvjs_.Pa=0;gvjs_.$O=!0;gvjs_q(gvjs_mc,gvjs_lT,void 0);gvjs_lT.prototype.draw=gvjs_lT.prototype.draw;gvjs_lT.prototype.clearChart=gvjs_lT.prototype.Jb;gvjs_lT.prototype.getContainer=gvjs_lT.prototype.getContainer;
